import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { TooltipProvider } from "./context/TooltipContext";
import { HeaderProvider } from "./context/HeaderContext";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Burnbox website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased h-[100vh] max-w-[100vw]`}>
        <TooltipProvider>
          <HeaderProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </HeaderProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
